name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style-client:
    name: Verify code style and quality (client)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Format check
        working-directory: client
        run: mise format-check

      - name: Lint
        working-directory: client
        run: mise lint

      - name: Analyze
        working-directory: client
        run: mise check
